# Generated by Django 5.1.3 on 2025-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_tour_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phonenumber', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('selected_tour', models.CharField(max_length=150, verbose_name='Your Selected Tour')),
                ('preferred_travel_date', models.DateField(verbose_name='Preferred Travel Date')),
                ('number_of_travelers', models.PositiveIntegerField(verbose_name='Number of Travelers')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
            ],
        ),
    ]
