# Generated by Django 5.1.3 on 2025-02-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tourbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='number_of_travelers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='preferred_travel_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='selected_tour',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
